# Build stage
FROM golang:1.24.1-bullseye AS builder

# Set working directory
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# # Build the application
# RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-food-calculator

FROM builder AS food-calculator-test
RUN go test ./... -v


# ENTRYPOINT ["/docker-food-calculator"]